
#
# Current setup:
# - All development is done in a fork.
# - Pull requests are merged into master and it auto publishes to the myget pre-release 'homely-oss' feed.
# - Tag 'master' to auto publishes to the nuget feed.
#


### ***********************************************************************************************************
### REQUIRED: AV UI => Project Settings -> General -> "Enable secure variables in all Pull Requests" TICKED ON.
### ***********************************************************************************************************


version: '{build}.0.0-dev'
configuration: Release
os: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true

# Override the 'version' if this is a GH-tag-commit -or- this is a custom branch (i.e not 'master').
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE -and $env:APPVEYOR_REPO_BRANCH -eq 'master')
      { 
          Write-Host " !! Commit is Tagged and branch is 'master' - forcing build version to tag-value." -ForegroundColor Red; 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))
  
before_build:
  # Display .NET Core version
  - cmd: dotnet --info
  # Display minimal restore text
  - cmd: dotnet restore --verbosity quiet

build_script:
  - dotnet build -c %CONFIGURATION% -v minimal /p:Version=%APPVEYOR_BUILD_VERSION% --no-restore
  - dotnet pack src\Homely.AspNetCore.Hosting.CoreApp\Homely.AspNetCore.Hosting.CoreApp.csproj -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION% --no-build

test: no

artifacts:
  - path: '**\*.nupkg'
    name: homely-nuget-packages
    type: NuGetPackage
  - path: '**\*.snupkg'
    name: homely-nuget-symbols
    type: NuGetPackage

deploy:
  # NOTE: MyGet doesn't support snupkg's so we have to manually specify the nuget to send
  - provider: NuGet
    server: https://www.myget.org/F/homely-oss/api/v2/package
    api_key:
      secure: Hjh+3kM8vuQOP1NCxEMJA85F4ieaRNNWxGo+I4dxxYAZdjaHLy7tVmxw7lLmqDke
    skip_symbols: true
    on:
      appveyor_repo_tag: false
    artifact: homely-nuget-packages
  
  # Note: No artifact was specified, so it will default to sending all NuGetPackage artifacts.
  - provider: NuGet
    api_key:
      secure: 36NxHYhJErlI2N+nlVlzxRPeNoujnX2l8JyCLgn48v+S3sEZfEesZSzB9W3QW3ZY
    skip_symbols: true
    on:
      branch: master
      appveyor_repo_tag: true
    
